#!/bin/sh
mkdir -p /proc /sys /dev
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

mkdir -p /mnt
mount /dev/vda /mnt 2>/dev/null || { mkfs.ext2 /dev/vda && mount /dev/vda /mnt; }

exec /bin/sh -i